# Generated by Django 3.2.19 on 2023-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizzazione',
            options={'verbose_name_plural': 'Organizzazioni'},
        ),
        migrations.AddField(
            model_name='unita',
            name='nome',
            field=models.CharField(default='---', max_length=255),
            preserve_default=False,
        ),
    ]
