# Generated by Django 3.2.19 on 2023-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230505_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatola',
            name='quantita',
        ),
    ]
