# Generated by Django 3.2.19 on 2023-05-07 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_scatola_quantita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unita',
            old_name='max_boxes',
            new_name='max_scatole',
        ),
        migrations.AlterField(
            model_name='utente_organizzazione',
            name='organizzazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organizzazione'),
        ),
        migrations.AlterField(
            model_name='utente_organizzazione',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
